const constants = {
	BEGIN_FETCH_POSTS: 'BEGIN_FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILED: 'FETCH_POSTS_FAILED',
	FETCH_SORTED_POSTS_SUCCESS: 'FETCH_SORTED_POSTS_SUCCESS',
  //
  ADD_POST: 'ADD_POST',
  //
  BEGIN_FETCH_CATEGORIES: 'BEGIN_FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED',
  //
  GET_SELECTED_CATEGORY: 'GET_SELECTED_CATEGORY',
  GET_SELECTED_POST: 'GET_SELECTED_POST',
  //
	BEGIN_FETCH_COMMENTS: 'BEGIN_FETCH_COMMENTS',
	FETCH_COMMENTS_FAILED: 'FETCH_COMMENTS_FAILED',
	FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
	ADD_COMMENT: 'ADD_COMMENT',
	GET_SELECTED_COMMENT: 'GET_SELECTED_COMMENT',
	FETCH_SORTED_COMMENTS_SUCCESS: 'FETCH_SORTED_COMMENTS_SUCCESS',
  //
  FETCH_POST_DETAIL: 'FETCH_POST_DETAIL',
  FETCH_POST_DETAIL_SUCCESS: 'FETCH_POST_DETAIL_SUCCESS',
  FETCH_POST_DETAIL_ERROR: 'FETCH_POST_DETAIL_ERROR',
	// EDIT_POST_DETAIL: 'EDIT_POST_DETAIL'
  //
}

export default constants
